### ISSUE TITLE
Context menu of notification area icon misaligned.

### ISSUE THREAD

**Issue by dongle-the-gadget** [michalleptuch/ink-workspace#14]
<img alt="Screenshot of Ink Workspace context menu being misaligned from the icon" src="https://user-images.githubusercontent.com/29563098/216652312-ca43be8f-6961-4c3e-9aac-c87b3fc79a04.png">

**Comment by michalleptuch** [comment]
Your screen shows Ink Workspace in normal version (1.xx).
Check junk folder. I sent an e-mail about Ink Workspace 2.0 Preview ;)
