### ISSUE TITLE
[Bug] Unable to update ink workspace

### ISSUE THREAD

**Issue by QWERT-commits** [michalleptuch/ink-workspace#16]
**Issue:** 
Cannot update ink workspace to version 2.0 (Mentioned in another issue) through Microsoft store. Reinstalling does not solve the problem. Author's app section was checked, but Ink Workspace 2.0 does not appear as another app release.

![image](https://user-images.githubusercontent.com/64510408/216763773-2ec6f82b-0a3e-4f11-abb2-e70e21c3f676.png)
[Microsoft Store update page after Ink Workspace was reinstalled]

![image](https://user-images.githubusercontent.com/64510408/216763898-bb444590-0264-4b46-9be1-643a869e6dcf.png)
[Author's app section in Microsoft Store]

![image](https://user-images.githubusercontent.com/64510408/216763918-90e0a8ac-0de1-42e9-9224-eb9620b625f2.png)
[Images of ink workspace 2.0 found in another issue]

**Environment:**
Current Ink Workspace version: 1.10.0
Windows version: 25290 Dev
Microsoft Store Version: 22212.1401.6.0

**Comment by michalleptuch** [comment]
Ink Workspace 2.0 is not available publicly. If you requested to join the testing program of Ink Workspace 2.0 just check your mailbox. If you don't see any e-mail about that, you have to wait for the official release later this year.
