### ISSUE TITLE
[Feature Request] Add Lottie animations to Ink Workspace 2.0 Settings Icons

### ISSUE THREAD

**Issue by EpicBProgrammingOnReddit** [michalleptuch/ink-workspace#18]
The Settings menu in Ink Workspace needs to have one more improvement, the colorized icons in the left side needs to be animated with Lottie. This will make it more focused and smoother just like they did in Windows 11 Settings app. Can you add this feature to a new preview update?

**Comment by michalleptuch** [comment]
Do you know an easy way to create these animations? 🙂

**Comment by EpicBProgrammingOnReddit** [comment]
https://learn.microsoft.com/en-us/windows/apps/design/controls/animated-icon

Custom animations can be created with Adobe After Effects and rendered with the Lottie-Windows library to use as an animated icon in your WinUI application.

**Comment by michalleptuch** [comment]
It's not WinUI 🙂 It's XAML Islands app (WPF + UWP). I have to get more information about Lottie animations in XAML Islands before I start creating such type of graphics.

**Comment by michalleptuch** [comment]
It's not an important feature at this moment. I will consider it in the future.
