### ISSUE TITLE
[Settings 2.0] Home and Apps pages still have dashes

### ISSUE THREAD

**Issue by dongle-the-gadget** [michalleptuch/ink-workspace#19]
<img width="902" alt="image" src="https://user-images.githubusercontent.com/29563098/218313356-f53554a3-c07e-48e0-b13f-aa850b35dc67.png">
<img width="902" alt="image" src="https://user-images.githubusercontent.com/29563098/218313347-2e353c05-7ed5-45d7-a5bd-ab1f32441029.png">

**Comment by michalleptuch** [comment]
Are you sure you have version 2023.212.0?
