### ISSUE TITLE
I see so much untapped potential here...

### ISSUE THREAD

**Issue by JosephInn** [michalleptuch/ink-workspace#2]
At the moment, this app serves as "one place for all the Inking apps+ some other features" and it lives exclusively on the Taskbar's tray area; It is in and of itself superbe at what it does, but I see so much more that could be done with what you have built. 

A bit a context: Every time I take a look at my overcrowded taskbar, I ask myself: wouldn't it be great to have apps Grouped by Categories, all my entertainment apps, all my video/ photo editing software, all my office apps, all my games, and so on... it would be like having a "Mini Start Menu" for all the different app Categories in my taskbar. 

Here, I did a quick mockup so you can get a better idea of what i mean:

![Mockup](https://user-images.githubusercontent.com/65547668/107530684-e1102780-6b9a-11eb-8132-f645bd710233.png)

**Comment by JosephInn** [comment]
I'm not suggesting that you change "Ink Workspace (Preview)" into this new behavior, but instead that you use your knowledge from what you've already built to create a new app; the name of said new app could be: "WORKSPACES"

**Comment by NotLT** [comment]
Totally agree , could serve as a duplicate start menu, if the ability to remove stock apps, and add your own as well as resizing tiles

**Comment by lorisobi** [comment]
This would be great, cause it could so also bring tiles to Win11

**Comment by michalleptuch** [comment]
I'm not sure if tiles are a good idea...
