### ISSUE TITLE
Captures doesn't playback in some apps

### ISSUE THREAD

**Issue by dongle-the-gadget** [michalleptuch/ink-workspace#20]
Captures from Ink Workspace (both v1 and v2) can't be played in some video players like Windows Media Player (Legacy works) and Photos.

**Comment by michalleptuch** [comment]
Does anyone else have the same problem?
It works on my side.
Windows 11 22621

**Comment by michalleptuch** [comment]
@dongle-the-gadget Does this issue still occur?

**Comment by dongle-the-gadget** [comment]
Yes, but it seems that all other video recording software trigger the same problem (including Snipping Tool).
