### ISSUE TITLE
error in how the panel is displayed

### ISSUE THREAD

**Issue by JoFry7784** [michalleptuch/ink-workspace#3]
my screen is 1920 x 1080 and when I open the app the panel shows out of the place where it should be
bug photo: 
<img width="592" alt="Captura de pantalla 2021-09-06 211851" src="https://user-images.githubusercontent.com/88383804/132274346-b2634bab-d8de-4cf5-87e1-322c934b76e1.png">

**Comment by michalleptuch** [comment]
Do you use one display or more?

**Comment by JoFry7784** [comment]
I don't know what happened but today the error no longer occurs, and answering your question I only use a monitor
