### ISSUE TITLE
Pro version is not available in Ukrainian Microsoft Store

### ISSUE THREAD

**Issue by Sominemo** [michalleptuch/ink-workspace#4]
There's no way to buy the Pro version in Ukrainian Microsoft Store, it says the item is not available

**Comment by michalleptuch** [comment]
Hi, it's correct behavior due to Microsoft Store policies. You can temporarily change region (set on United States) on your device and then reopen Microsoft Store to buy this app. Accept my apologies for any inconvenience 😉

**Comment by Sominemo** [comment]
I'm afraid it won't accept my payment method in US MS Store

**Comment by michalleptuch** [comment]
@Sominemo Ink Workspace Pro is now available globally 😉
