### ISSUE TITLE
Cannot open ink workspace 2 preview in 25309

### ISSUE THREAD

**Issue by ZHang233-ai** [michalleptuch/ink-workspace#52]
Previous version can open it successfully,but installed the latest verison can't.

**Comment by michalleptuch** [comment]
Is it working? You closed the issue :)

**Comment by ZHang233-ai** [comment]
I restart the system,and it worked.Thanks.😊
________________________________
发件人: Michał Łeptuch ***@***.***>
发送时间: 2023年3月7日 23:52
收件人: michalleptuch/ink-workspace ***@***.***>
抄送: ZHang233-ai ***@***.***>; State change ***@***.***>
主题: Re: [michalleptuch/ink-workspace] Cannot open ink workspace 2 preview in 25309 (Issue #52)


Is it working? You closed the issue :)
