### ISSUE TITLE
Request: Combine Pinyin character and Alphabet character in app list

### ISSUE THREAD

**Issue by ZHang233-ai** [michalleptuch/ink-workspace#53]
![image](https://user-images.githubusercontent.com/61895383/224520153-ff5b9633-cf7d-486e-9cea-f09c343dd813.png)
![image](https://user-images.githubusercontent.com/61895383/224520169-4b4b509b-da50-4b5e-b892-c8fadec02a7e.png)

**Comment by michalleptuch** [comment]
What is the expected result? I see the same situation is the Start menu:
<img width="600" alt="image" src="https://user-images.githubusercontent.com/43097852/224821447-10704438-7370-4c03-a2ea-b3ee1c944ef8.png">

**Comment by ZHang233-ai** [comment]
It should be like this.
________________________________
发件人: Michał Łeptuch ***@***.***>
发送时间: 2023年3月14日 4:12
收件人: michalleptuch/ink-workspace ***@***.***>
抄送: ZHang233-ai ***@***.***>; Author ***@***.***>
主题: Re: [michalleptuch/ink-workspace] Request: Combine Pinyin character and Alphabet character in app list (Issue #53)


What is the expected result? I see the same situation is the Start menu:
[image]<https://user-images.githubusercontent.com/43097852/224821447-10704438-7370-4c03-a2ea-b3ee1c944ef8.png>

**Comment by michalleptuch** [comment]
You should explain me this in a better way ;) I'm non-Chinese guy, sorry

**Comment by ZHang233-ai** [comment]
________________________________
发件人: Michał Łeptuch ***@***.***>
发送时间: 2023年3月14日 22:30
收件人: michalleptuch/ink-workspace ***@***.***>
抄送: ZHang233-ai ***@***.***>; Author ***@***.***>
主题: Re: [michalleptuch/ink-workspace] Request: Combine Pinyin character and Alphabet character in app list (Issue #53)


You should explain me this in a better way ;) I'm non-Chinese guy, sorry

**Comment by michalleptuch** [comment]
https://edi.wang/post/2016/9/22/windows-10-uwp-fark-pinyin-group

**Comment by ZHang233-ai** [comment]
![image](https://github.com/michalleptuch/ink-workspace/assets/61895383/b2bc6e8c-f923-4896-8171-94beec238a02)
![image](https://github.com/michalleptuch/ink-workspace/assets/61895383/b851d1b9-bfbb-4474-b306-4b083f69b82a)
Do you know why this app can't combine to B?

**Comment by michalleptuch** [comment]
Could you send me the name of this app? It will be more helpful than screenshot :)

**Comment by ZHang233-ai** [comment]
> Could you send me the name of this app? It will be more helpful than screenshot :)

哔哩(Bili)

**Comment by michalleptuch** [comment]
I don't know if I can fix it. I followed this article: https://www.cnblogs.com/glacierh/archive/2008/08/25/1276113.html and checked the algorithm. 

For this name '哔哩' I got first letter (two bytes) with values: 223 and 217 but they don't match the range for B letter:

<img width="539" alt="image" src="https://github.com/michalleptuch/ink-workspace/assets/43097852/fac15c94-305e-4075-93d3-91e5e82e0f91">

**Comment by ZHang233-ai** [comment]
> 

yes

**Comment by michalleptuch** [comment]
It will be fixed in the next release.
