### ISSUE TITLE
Make installer (setup)

### ISSUE THREAD

**Issue by xmha97** [michalleptuch/ink-workspace#6]
I want to install [ink-workspace](https://github.com/michalleptuch/ink-workspace) without Microsoft Store on Windows 10 Enterprise LTSC.

**Comment by michalleptuch** [comment]
Which version of LTSC do you have?

**Comment by xmha97** [comment]
Microsoft Windows 10 Enterprise LTSC 2021 Version 21H2 Build 19044.1288 MSDN x64
https://downloadly.net/2020/10/1422/03/windows-10-ltsc/02/?#/1422-windows-142234025411.html
