### ISSUE TITLE
Feature Request: Pen status panel

### ISSUE THREAD

**Issue by Sominemo** [michalleptuch/ink-workspace#7]
If it's possible, would be great to have a pen status panel so you could see if it is connected by Bluetooth and its battery charge. Kinda like the Windows settings tile under Devices.
![image](https://user-images.githubusercontent.com/19842935/158066395-83858754-8310-44c9-b84f-f6335488c278.png)

**Comment by michalleptuch** [comment]
Microsoft plans to add Bluetooth panel that will be similar to Wi-Fi panel. I believe that it will be better solution for you 😊

![image](https://user-images.githubusercontent.com/43097852/158455593-85af44b9-e8ac-4b0d-8c14-2aff2803e20e.png)

**Comment by michalleptuch** [comment]
It will be included in Ink Workspace 2.0.
