### ISSUE TITLE
Version 2.3.0 Transparency Issues

### ISSUE THREAD

**Issue by Octur1s** [michalleptuch/ink-workspace#78]
After updating ink workspace to version 2.3.0 from the Microsoft store, the app is very transparent, and the right border is wider than the left.

Windows 10 22H2

![image](https://github.com/michalleptuch/ink-workspace/assets/118348776/c67af1ab-ddc4-4b22-ace7-af4b573d6833)

**Comment by michalleptuch** [comment]
Did you try to reinstall the app?

**Comment by Octur1s** [comment]
Unfortunately reinstalling didn't resolve the issue

Windows 10 Build 19045.3208

![image](https://github.com/michalleptuch/ink-workspace/assets/118348776/2d5de77a-1d17-4bc4-bcdc-5e203a4b6cf5)

**Comment by michalleptuch** [comment]
Try to update app to version 2.3.1.

**Comment by Octur1s** [comment]
That fixed it, thank you!
