### ISSUE TITLE
Section titles remain black after disabling the dark mode on Windows 11

### ISSUE THREAD

**Issue by Artaherzadeh** [michalleptuch/ink-workspace#8]
![Screenshot (125)](https://user-images.githubusercontent.com/64541682/158314942-92a64719-7192-499f-adf4-222271359df4.png)

**Comment by michalleptuch** [comment]
Could you tell me which version of my app do you use?

**Comment by Artaherzadeh** [comment]
I'm using the latest version on Microsoft Store.
