### ISSUE TITLE
Sometimes when I scroll up and down using the mouse wheel and mouse pointer is on the app , it changes screen brightness.

### ISSUE THREAD

**Issue by Artaherzadeh** [michalleptuch/ink-workspace#9]
I'm using Twinkle Tray app. Maybe Ink Workspace and Twinkle Tray are not compatible together.

**Comment by michalleptuch** [comment]
Perhaps Twinkle Tray has a bug. Ink Workspace doesn't allow to change screen brightness.

**Comment by Artaherzadeh** [comment]
I don't know. I have been using Twinkle Tray since 5-6 month ago and never
had this issue before.
